name: LRA-FORMATTING

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  verify-format:
    name: Verify format
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 17 # minimum supported JDK

      - name: Verify pull request format
        run: ./mvnw formatter:validate
